### ISSUE TITLE
Launching tasks with image defined entrypoint

### ISSUE THREAD

**Issue by keis** [klarna/eremetic#100]
By default mesos will prefix the command with `/bin/sh -c` and ignore the entrypoint specified in the image. It's possible to tune this in the [CommandInfo](https://github.com/mesos/mesos-go/blob/master/mesosproto/mesos.pb.go)

I suggest we follow marathons convention of differentiating between the two modes by the field used `cmd` or `args`.  https://mesosphere.github.io/marathon/docs/native-docker.html (Command vs Args)

**Comment by marcusolsson** [comment]
Just to clarify, given that

```
ENTRYPOINT ["echo"]
CMD ["hello"]
```

_Example 1:_
```
{
    "cmd": "ping"
}
```
should result in: `sh -c ping`

_Example 2:_
```
{
    "args": ["ping"]
}
```
should result in: `echo ping`

Correct?
