### ISSUE TITLE
Pushing to docker hub?

### ISSUE THREAD

**Issue by damomurf** [klarna/eremetic#101]
Assuming that alde/eremetic is the canonical docker repository for Eremetic, is there any chance v0.21.0 and v0.22.0 could be pushed up there? We need the slave constraint support and would prefer not to diverge from the "official" image.

**Comment by keis** [comment]
it is and there should be an automatic build publishing each tagged version. I'll look into what's broken.

thanks for the heads up

**Comment by keis** [comment]
I've published a v0.22.2 now that is also on docker hub as it should be :)

**Comment by damomurf** [comment]
Awesome, thanks!
