### ISSUE TITLE
Add a `TASK_QUEUED` state

### ISSUE THREAD

**Issue by sheepkiller** [klarna/eremetic#110]
Hi,

I'm using eremetic to launch jobs on an autoscale group of slaves, and sometimes. jobs are waiting in the queue for a while. Currently `TASK_STAGING` state is not precise enough, since status is set when the task is created in the queue, not launched on mesos.
Here's what I propose:
- When `NewEremeticTask` is called, set the task status to `TASK_QUEUED`
- When `createTaskInfo` is call, status is updated to add `TASK_STAGING` 
- If task failed and is elligible for a retry, `StatusUpdate` will update status to `TASK_QUEUED`

thanks

**Comment by keis** [comment]
The only problem is that we use `mesos.TaskState_` constants all over so it would be a bit confusing to simply add this state. We would have to define our own task state enum that we can use for everything except talking mesos protobuf.

Should not be to messy I think I'm +1 on this

**Comment by sheepkiller** [comment]
Do you mean having a simple wrapper function which would be called for every status update?

This function would return the string of the state. Basically, since TaskStatus_* are int32, all Eremetic task status could be negative to avoid conflict in the future. 
Here the pseudo code.
in types package:
const (
Eremetic_TaskStatus_TASK_QUEUED -1
Eremetic_TaskStatus_TASK_REMOVED_FROM_QUEUE -2
Eremetic_TaskStatus_TASK_EXPIRED -3
...
)

func GetEremeticStatusString(status uint32) string {
if status >= 0 {
check and return mesos task status string
} else {
check and return eremetic task status string
}
}

**Comment by keis** [comment]
Something like that but I would make the eremetic states a super set of the mesos states. This way we could always treat the values as eremetic states because TASK_STAGING etc will be the same in both namespaces.

And looks like in most places we're only dealing with the string representation of the states so we could even get away with not assigning them integers at all.

**Comment by sheepkiller** [comment]
Thank you !
