### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by mrares** [klarna/eremetic#128]
While trying make with code past 2f4773f15c156e3d01efb16111b120a3a8f78569:

can't load package: /gocode/src/github.com/klarna/eremetic/server/handler.go:16:2: import "github.com/klarna/eremetic" is a program, not an importable package

**Comment by marcusolsson** [comment]
What command are you using to build?

**Comment by mrares** [comment]
make docker/eremetic

**Comment by mrares** [comment]
bash-4.2# go version
go version go1.6.3 linux/amd64

**Comment by mrares** [comment]
bash-4.2# pwd
/gocode/src/github.com/klarna/eremetic
bash-4.2# env
HOSTNAME=0dd7cc86da65
TERM=xterm
OLDPWD=/opt/eremetic
GOCODE=/gocode
http_proxy=http://webproxy:3128/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/gocode/bin
PWD=/gocode/src/github.com/klarna/eremetic
https_proxy=http://webproxy:3128/
SHLVL=1
HOME=/root
GOPATH=/gocode
_=/usr/bin/env

**Comment by marcusolsson** [comment]
I have tried reproducing your issue for Go 1.7 and 1.6 but is unable to do so. In the commit you mentioned, the `main` package was moved to `cmd/eremetic` and it sounds like somehow your import path refers to an older version where the root package was executable. Could you make sure you don't have any old versions lying around?

**Comment by mrares** [comment]
I had a left-over bindata_assetfs.go apparently

**Comment by keis** [comment]
Sounds like you got it working so I'm closing the issue. Please re-open if you have further issues getting it to build.
