### ISSUE TITLE
task REST endpoint returning 'null' instead of 404

### ISSUE THREAD

**Issue by icastro28** [klarna/eremetic#135]
While testing the REST endpoints provided, I noticed that when the GET /task endpoint is called, and no tasks are currently RUNNING, the response code is wrong since I'm getting a 200 code with 'null' value in the body, instead of getting a 404 as specified in the Swagger.yaml file.

**Comment by keis** [comment]
Nice catch @icastro28 

Returning null is super weird. 200 is IMHO more correct as the list of running tasks still exists even when it is empty. But regardless we should update one or both so that the documentation is correct.

**Comment by icastro28** [comment]
Fair enough, but yeah null is not good.

**Comment by sheepkiller** [comment]
hi @icastro28 ,

which version are you running ? PR #115 should have fixed that (200 + empty array). Maybe there's a regression somewhere.

**Comment by keis** [comment]
Aha, I thought it sounded familiar. Looks like it didn't make it into a tagged release up until recently.

@alde Did you get 0.24 to work?

**Comment by alde** [comment]
@keis: yes, as far as I could test. Tagged 0.24.1 with the fix.

**Comment by icastro28** [comment]
I didn't use a specifix tag, I used latest.

Ivan
