### ISSUE TITLE
proposal: merge scheduler into eremetic pkg

### ISSUE THREAD

**Issue by marcusolsson** [klarna/eremetic#139]
In https://github.com/klarna/eremetic/pull/126, the `types` package was moved to form the `eremetic` package. Currently though, the `eremetic` package still only consist of types and no logic. Because of this, it doesn't really pull its own weight at the moment. 

Meanwhile, the core functionality of eremetic is really located in the `scheduler` package, which becomes a bit redundant since Eremetic at its core, _is_ a scheduler.

Core functionality should gravitate towards the root package, as sub-packages typically signal auxillary functionality that serve that core domain (like the `boltdb` and `zk` adapters).

I propose that the `scheduler` package is merged into the root `eremetic` package to better communicate purpose and intention. 

I would be happy to submit a PR with these changes if you agree it to be an improvement.

**Comment by alde** [comment]
I am inclined to agree. I am aware that the package layout was not entirely go:ish from the start :-)

**Comment by marcusolsson** [comment]
We learn as we go. Being idiomatic is not guaranteed to make any given application better, but it does provide familiarity to people who might want to contribute to the project :)

**Comment by alde** [comment]
Solved in #142
