### ISSUE TITLE
Tasks stuck in TASK_QUEUED

### ISSUE THREAD

**Issue by mheppner** [klarna/eremetic#153]
I created a pretty basic DC/OS package that uses [alde/eremetic:latest](https://hub.docker.com/r/alde/eremetic/), but every task I launch stays in the `TASK_QUEUED` state. No matter what image I try to launch in Eremetic, everything always stays queued.

Here's what I was POSTing to Eremetic, which returns a task ID:
```json
{
    "task_cpus": 1.0,
    "task_mem": 512,
    "docker_image": "centos/centos7",
    "force_pull_image": true,
    "command": "ls -l / && echo $TEST",
    "env": {"TEST": "myvalue"}
}
```

In the DC/OS package, I set these environment variables for running alde/eremetic:
```
HOST=0.0.0.0
PORT=8000
LOGLEVEL=DEBUG
MASTER=zk://zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181/<znode>
```
Some of the contents from stderr:
```
time="2017-01-23T17:24:09Z" level=info msg="Launching Eremetic version 0.26.0!\nListening to 0.0.0.0:8000" address=0.0.0.0 port=8000 version=0.26.0 
ERROR: logging before flag.Parse: I0123 17:24:09.957588       1 scheduler.go:334] Initializing mesos scheduler driver
ERROR: logging before flag.Parse: I0123 17:24:09.957682       1 scheduler.go:833] Starting the scheduler driver...
ERROR: logging before flag.Parse: I0123 17:24:09.957739       1 http_transporter.go:383] listening on 0.0.0.0 port 43756
ERROR: logging before flag.Parse: I0123 17:24:09.957756       1 scheduler.go:850] Mesos scheduler driver started with PID=scheduler(1)@10.3.2.155:43756
ERROR: logging before flag.Parse: I0123 17:24:09.964734       1 scheduler.go:1053] Scheduler driver running.  Waiting to be stopped.
2017/01/23 17:24:09 Connected to 10.3.2.150:2181
2017/01/23 17:24:09 Authenticated: id=97220057631566541, timeout=40000
2017/01/23 17:24:09 Re-submitting `0` credentials after reconnect
time="2017-01-23T17:24:13Z" level=debug msg="Fetching all tasks"
```

That error message looks like it was successful, and then it does say it connected to port 2181.

**Comment by mheppner** [comment]
I set `traefik.portIndex` to 0 as a label, and relaunched specifying the container <-> host port mapping to 0. However, that portMapping only exists the first time it gets launched. If you relaunch it, that goes away, and it never gets registered to Mesos as a framework.

What is the 0:0 portMapping for and why does it disappear?

**Comment by keis** [comment]
The second port is used as the libprocess transport port which is needed to receive offers from mesos. port 0 only means to map any port and we expect the port number of this to be $PORT1 (marathon.sh)

the label shouldn't matter unless you're also using traefik to do load balancing.

**Comment by mheppner** [comment]
I wasn't clear before, but I solved it by setting the traefik label and the 0:0 portMapping.

Any idea why the portMapping goes away? This is an issue in DC/OS/Marathon if the app gets restarted. Can a fixed value be set?

**Comment by keis** [comment]
No idea, I have never seen anything like that happen. Setting a fixed value should work but you have to make sure it's a 1-to-1 mapping between the container and host because the same port number is used when registering.

**Comment by mheppner** [comment]
I'm using DC/OS 1.8 enterprise and the port mapping goes away after it gets assigned. When the Eremetic package first starts up, two random ports show up. After a few minutes, the second port goes away from the UI. Everything still works. When you restart the service, the second port never gets assigned, so maybe DC/OS thinks the port was already there. Setting a fixed port mapping fixes this problem though.

Great framework though, I highly suggest adding it to the official [mesosphere/universe](https://github.com/mesosphere/universe)! I can give you a gist of our package if needed.
