### ISSUE TITLE
Tasks are stuck with status TASK_QUEUED 

### ISSUE THREAD

**Issue by buyology** [klarna/eremetic#156]
Trying to run the [examples](https://github.com/klarna/eremetic/blob/master/examples.md#examples)  [with your suggested Mesos setup](https://github.com/klarna/eremetic#running-on-mesos), but all tasks just end up with status TASK_QUEUED

Any pointers to how to debug this?

**Comment by keis** [comment]
This typically means eremetic is not getting any resources offers from mesos. You can try setting the log level to debug and see if something looks off. It could be it's registering with the wrong address or port

**Comment by buyology** [comment]
PEBKAC: missed changing the zookeeper IPs
