### ISSUE TITLE
DCOS Package

### ISSUE THREAD

**Issue by gisjedi** [klarna/eremetic#164]
Does the team have any interest in an eremetic package in the DCOS Universe (https://github.com/mesosphere/universe)? We've built one and would be happy to submit and maintain on your behalf. We've found eremetic very useful for our one-shot job needs and there were a few little gotchas with the Marathon / DCOS config that are eliminated by the package we created.

**Comment by keis** [comment]
that sounds excellent to have. do you need anything from us to submit that?

also would be interesting to know what the gotchas are so that perhaps we could work around them.

**Comment by gisjedi** [comment]
Main issue is when using the sample `marathon.json` the `hostPort` and `containerPort` values set to 0 get swallowed on creation and a Marathon restart of the eremetic service strips that port map. This results in a half-way running eremetic - service available, but communication with Mesos is broken. Our solution was to pin to an explicit `hostPort` and `containerPort` value - we chose 41149. Why that number... it is not tied to any common service applications and its the concatenated numerical cipher values of `herm`(short for hermit) shifted with 1 being `e`: 4 1 14 9

We also chose to use zookeeper for eremetic DB and set the queue size to 1,000,000 - yeah, we are running a lot of jobs. This gave us _much_ better job submittal rates and allowed us to entirely saturate our sizable cluster with jobs. I'd planned to set the default queue size to 10k as a default.

I'll just submit a PR directly to the DCOS universe and let you guys know when its approved. I've gotten a few packages added previously, so it should be a pretty straight forward process. I'll need to make a couple variants of the eremetic logo for different portions of their UI, which I can add to your repo in a PR or just stick in an asset repo (https://github.com/appliedis/universe-assets) I've used previously - your choice. I'll be directly targeting your `alde/eremetic:0.26.0` Docker image for the package, unless you prefer another one.

**Comment by keis** [comment]
ok. right I recall that now. must be some dcos oddity. 

please send a PR for adding the logos to this you never know when those might be useful.

and you got the right docker repo as this is where our automatic build is pushing.

**Comment by alde** [comment]
Sounds awesome. Let us know if you need any help from us.

**Comment by gisjedi** [comment]
Okay, I've got one issue that I need some feedback on. When I deploy Eremetic behind the DCOS Admin Router it is exposed on a non-root context `/service/eremetic/`, which results in 404 to all the assets as they have absolute references. Is there a header or something that the Eremetic server accepts that could shim in the additional portion of the URL added by the reverse proxy?

![adminrouterissue](https://cloud.githubusercontent.com/assets/4768496/24757316/dd364e84-1aac-11e7-861a-9a40fbd8c71f.PNG)

**Comment by keis** [comment]
hmm no, we can deal with `X-Forwarded-Proto` but nothing more fancy. But should not be too complicated to support. I'm not aware of any (pseudo-) standard for doing that so maybe we could just align to what others are doing for the dcos admin

**Comment by gisjedi** [comment]
Most backend services that I've worked with have the concept of a URL prefix for handling this sort of thing. I believe it just needs to update the https://github.com/klarna/eremetic/blob/master/server/routes.go to prefix the URL. This could be easily accomplished with an optional environment variable added to https://github.com/klarna/eremetic/blob/master/config/config.go that is consumed by the route handler file. Does something like that sound doable?

**Comment by gisjedi** [comment]
As a side note, we've always either used internal VIPs or subdomains VHOSTs via Marathon LB to expose Eremetic which doesn't raise this URL prefix problem. I'd like to avoid making configuration of a load balancer and DNS entries a prerequisite for package users, which is why I'm trying to make everything work with the built in DCOS Admin Router.

**Comment by keis** [comment]
Yeah, sounds good. I think this would have to go both in server/templates and the urlFor helper (for the api location headers etc)

**Comment by gisjedi** [comment]
Universe package is submitted: https://github.com/mesosphere/universe/pull/1113

I'll update once it's approved.

**Comment by gisjedi** [comment]
Universe package has been merged and can be found here: 

https://universe.serv.sh/#/package/eremetic/version/latest

Documentation for testing via DC/OS is found here: 

https://github.com/dcos/examples/tree/master/eremetic

Updates of the Universe package will need to be made corresponding with each Eremetic release. Updates of the examples will need to be done with each DC/OS release. The Universe repo has detailed instructions on the process for making updates. If you need any assistance just mention me in or assign on issue on the next release.

**Comment by keis** [comment]
Yay, awesome stuff @gisjedi 👍
