### ISSUE TITLE
Private Docker repository support

### ISSUE THREAD

**Issue by heww** [klarna/eremetic#46]
Can eremetic accept uris paramter in  task POST API so that we can run task from image of private docker registry? 

```go
	task := types.EremeticTask{
		ID:       taskId,
		TaskCPUs: request.TaskCPUs,
		TaskMem:  request.TaskMem,
		Name:     request.Name,
		Status:   status,
		Command: &mesos.CommandInfo{
			Value: proto.String(request.Command),
			User:  proto.String("root"),
			Environment: &mesos.Environment{
				Variables: environment,
			},
			Uris: xxx // uris here
		},
		Container: &mesos.ContainerInfo{
			Type: mesos.ContainerInfo_DOCKER.Enum(),
			Docker: &mesos.ContainerInfo_DockerInfo{
				Image: proto.String(request.DockerImage),
			},
			Volumes: volumes,
		},
	}
```

And then POST a task like this

```shell
curl -H "Content-Type: application/json" \
     -X POST \
     -d '{"task_mem":22.0, "task_cpus":1.0, "docker_image": "a_private_docker_registry_image", "command": "rails", "uris": ["file:///etc/docker.tar.gz"]}' \
     http://eremetic_server:8080/task
```

**Comment by keis** [comment]
Sure. Setting the URIs of the command makes sense to expose through the api.

I don't get how that is related to using private docker registries though. We've been using a private registry from the beginning without problems and we simply set the docker_image to be e.g "private_docker_registry.local/image-name"

**Comment by heww** [comment]
I test that if the docker_image in private docker registry is private (which need to login private registry to pull), then task will failed.

![tasks](https://cloud.githubusercontent.com/assets/5634205/12002052/965adc60-ab30-11e5-82f2-d662faab29f0.jpg)

In the screenshot, the tasks eremetic-task.baeeb1ba-641f-491e-9210-997ba2e94009 which using private image failed(In fact that it don't start at all)

http://mesos.apache.org/documentation/latest/docker-containerizer/  say that using uris pointing to a .dockercfg (old docker version, current docker 1.9.1 using .docker/config.json ) that contains login information can run a image from a private repository.

**Comment by keis** [comment]
Ok. I guess we never ran into that because we have anonymous read access.

I'll take a look at this after the festive season :tada:

**Comment by keis** [comment]
as of 0.11.0 it's possible to specify uris to download. Could you verify this resolves the issue for you?

**Comment by keis** [comment]
Closing this now as this should be fixed. Open it again if you are still having issues.

**Comment by stefanobaghino** [comment]
I'm currently experiencing the same problem, but from my understanding it's perhaps already possible to do this: how can authentication credentials be provided for private registries that require one?

**Comment by keis** [comment]
So the way we discussed here si to provide a .dockercfg to be downloaded into the sandbox using `fetch` in the manifest you send to eremetic.

Looks like in newer versions of mesos you can also set a agent wide dockercfg

See the docs here http://mesos.apache.org/documentation/latest/docker-containerizer/

**Comment by stefanobaghino** [comment]
Uh, sorry, I missed that part of the comment. I'll try this out, thanks for the help!

**Comment by stefanobaghino** [comment]
As a follow up to my question, I'd like to report that what you suggested worked, thanks!

**Comment by alde** [comment]
Glad to hear it!
