### ISSUE TITLE
Specify attributes when creating tasks

### ISSUE THREAD

**Issue by chuckg** [klarna/eremetic#78]
Super useful for splitting clusters of resources or for running commands against specific hosts.

Attributes are key/value pairs can be applied to slaves. See:
http://mesos.apache.org/documentation/latest/configuration/

**Comment by keis** [comment]
I think this is something eremetic should support. I'm not entirely sure how the api should look though. marathon has a kinda sophisticated [contraint language](https://mesosphere.github.io/marathon/docs/constraints.html) for this. Only **like** and **unlike** is relevant for us.

We could mimic that our use some simple model of our own.

@alde ?

**Comment by alde** [comment]
Since we only really want like and unlike, I'd like to see if we can make something simpler than the marathon model.

**Comment by keis** [comment]
Was thinking about this a bit and maybe we should start out by only supporting a very simple "has attribute x equal to y" scenario. I implemented a quick and dirty matcher for it and it should be easy enough to wire up to the api.

**Comment by chuckg** [comment]
@keis: I have a working branch already doing that exact thing. It accept muliple ANDs:
https://github.com/klarna/eremetic/compare/master...chuckg:feature/task_attribute_constraints

**Comment by keis** [comment]
All right, cool stuff @chuckg. did not think to check the network list first hehe.

Could you open a pull request for that?

**Comment by alde** [comment]
@chuckg nice :) 👍

**Comment by chuckg** [comment]
@keis: absolutely, I will open a PR soon.
