### ISSUE TITLE
List all tasks, not just NonTerminal

### ISSUE THREAD

**Issue by alde** [klarna/eremetic#95]
Add a ?includeTerminal=true to /task resource to list all tasks.

Pagination?
Full data or subset and link to full data?

**Comment by keis** [comment]
What is the use case?

TBH I think this is an anti-feature. It would have a lot of implications on data retention and what promises we are making about the task data but also listing all historical tasks is potentially a very expensive request. We have the same problem with the current list task but there we at least have the possibility of optimising by keeping an index of running tasks

**Comment by alde** [comment]
Good points. It was just a thought that struck me, because it felt a bit weird with the /task endpoint listing things, but not everything.
